export const PUZZLE_MOVE_ANIMATION_MS = 128;
export const PUZZLE_SPAWN_POP_MS = 112;

export const PUZZLE_MOVE_ANIMATION_SECONDS = PUZZLE_MOVE_ANIMATION_MS / 1000;
export const PUZZLE_SPAWN_POP_SECONDS = PUZZLE_SPAWN_POP_MS / 1000;

export const PUZZLE_MOVE_EASE = [0.22, 1, 0.36, 1] as const;
